#!/usr/bin/env python2

# Copyright (C) 2015 East Asian Observatory
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful,but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,51 Franklin
# Street, Fifth Floor, Boston, MA  02110-1301, USA

"""
make_affiliations - Export affiliations file from Hedwig database

Usage:
    make_affiliations [-v | -q] --semester <semester> --queue <queue> [--output <filename>]

Options:

    --semester <semester>    Semester code
    --queue <queue>          Queue code
    --output, -o <filename>  Output filename
    --verbose, -v            Increase verbosity
    --quiet, -q              Decreate verbosity
"""

from __future__ import absolute_import, division, print_function, \
    unicode_literals

from codecs import utf_8_decode
from collections import OrderedDict
import logging
import sys

from docopt import docopt

from hedwig.config import get_database, get_facilities
from hedwig.util import get_logger
from hedwig.type import ProposalState

from hedwig2omp.config import get_config
from hedwig2omp.affiliation_file import write_affiliation_file


def main():
    args = docopt(__doc__)

    telescope = 'JCMT'
    semester_code = utf_8_decode(args['--semester'])[0]
    queue_code = utf_8_decode(args['--queue'])[0]

    logging.basicConfig(level=(logging.DEBUG if args['--verbose']
                               else (logging.WARNING if args['--quiet']
                                     else logging.INFO)))
    logger = get_logger('make_proj_def')

    logger.debug('Reading configuration')
    config = get_config()

    if config.has_option('queue_country', queue_code):
        country = config.get('queue_country', queue_code)
    else:
        country = queue_code

    logger.debug('Connecting to Hedwig database')
    db = get_database()
    (facility_class,) = get_facilities(facility_spec=telescope)
    facility_id = db.ensure_facility(facility_class.get_code())
    facility = facility_class(facility_id)

    logger.debug('Finding accepted proposals for this call')
    call_id = None
    queue_id = None
    affiliations = None
    assignments = OrderedDict()
    for proposal in db.search_proposal(
            facility_id=facility_id,
            semester_code=semester_code,
            queue_code=queue_code,
            state=ProposalState.ACCEPTED,
            with_members=True).values():
        code = facility.make_proposal_code(db, proposal)

        if affiliations is None:
            call_id = proposal.call_id
            queue_id = proposal.queue_id
            affiliations = db.search_affiliation(
                queue_id=queue_id, hidden=False, with_weight_call_id=call_id)

        elif (call_id != proposal.call_id) or (queue_id != proposal.queue_id):
            logger.error('Call or queue mismatch')
            sys.exit(1)

        # Compute affiliation fractions.
        assignments[code] = facility.calculate_affiliation_assignment(
            db, proposal.members, affiliations)

    logger.debug('Writing affiliations file')
    write_args = (affiliations, assignments)
    if args['--output'] is None:
        write_affiliation_file(sys.stdout, *write_args)
    else:
        with open(args['--output'], 'w') as file_:
            write_affiliation_file(file_, *write_args)

if __name__ == '__main__':
    main()
